swagger: "2.0"
info:
  title: "Swagger Example"
  description: >
    This is an example Koa API.
  version: "1.0.0"
host: "localhost:3000/api"
schemes:
  - "http"
paths:
  /movies:
    get:
      summary: "Listar Peliculas"
      description: "Listar todas las peliculas"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Servicio es correcto"
          schema:
            $ref: '#/definitions/Movie'
        500:
          description: "Servicio es incorrecto"

responses:
  500:
    description: Internal Server Error

definitions:
  Movie:
    type: "object"
    properties:
      _id:
        type: "string"
      title:
        type: "string"
      year:
        type: "string"
      released:
        type: "string"
      genero:
        type: "string"
      director:
        type: "string"
      actors:
        type: "string"
      plot:
        type: "string"
      ratings:
        type: "string"